= Links

== Services

https://www.paperspace.com/[Paperspace]

== Databases

https://www.youtube.com/channel/UCHnBsf2rH-K7pn09rb3qvkA/playlists[CMU Database Group]

== Coursera

https://www.coursera.org/specializations/big-data[Big Data Specialization @ *Coursera*] +
https://www.coursera.org/specializations/statistics[Statistics with R Specialization @ *Coursera*]
https://www.coursera.org/specializations/machine-learning-data-analysis[Машинное обучение и анализ данных Specialization @ *Coursera*] +
https://www.coursera.org/specializations/aml[Advanced Machine Learning Specialization @ *Coursera*] +
https://www.coursera.org/specializations/c-plus-plus-modern-development[Искусство разработки на современном C++ Specialization @ *Coursera*] +
https://www.coursera.org/specializations/recommender-systems[Recommender Systems Specialization @ *Coursera*] +
https://www.coursera.org/specializations/deep-learning[Deep Learning Specialization @ *Coursera*] +
https://www.coursera.org/specializations/data-structures-algorithms[Data Structures and Algorithms Specialization @ *Coursera*] +
https://www.coursera.org/specializations/probabilistic-graphical-models[Probabilistic Graphical Models Specialization @ *Coursera*] +
https://www.coursera.org/specializations/self-driving-cars[Self-Driving Cars Specialization @ *Coursera*] +
https://www.coursera.org/specializations/robotics[Robotics Specialization @ *Coursera*] +
https://www.coursera.org/specializations/modernrobotics[Modern Robotics: Mechanics, Planning, and Control Specialization @ *Coursera*] +
https://www.coursera.org/specializations/spacecraft-dynamics-control[Spacecraft Dynamics and Control Specialization @ *Coursera*] +
https://www.coursera.org/learn/kinematics[Кинематика @ *Coursera*] +
https://www.coursera.org/learn/discrete-optimization[Discrete Optimization @ *Coursera*] +
https://www.coursera.org/learn/linear-models[Advanced Linear Models for Data Science 1: Least Squares @ *Coursera*] +
https://www.coursera.org/learn/linear-models-2[Advanced Linear Models for Data Science 2: Statistical Linear Models @ *Coursera*] +
https://www.coursera.org/learn/datasciencemathskills[Data Science Math Skills @ *Coursera*] +
https://www.coursera.org/learn/bayesian-statistics[Bayesian Statistics: From Concept to Data Analysis @ *Coursera*] +
https://www.coursera.org/learn/machine-learning[Machine Learning @ *Coursera*] +
https://www.coursera.org/learn/vvedenie-mashinnoe-obuchenie[Введение в машинное обучение @ *Coursera*] +
https://www.coursera.org/learn/game-theory-1[Game Theory @ *Coursera*] +
https://www.coursera.org/learn/game-theory-2[Game Theory II: Advanced Applications @ *Coursera*] +

== Machine Learning

https://dlcourse.ai/[Deep Learning на пальцах] +
https://mlcourse.ai/[Open Machine Learning Course] +
http://ai.lector.ru/[Лекции по искусственному интеллекту и машинному обучению] +
http://work.caltech.edu/telecourse.html[Learning From Data @ *Caltech*] +
http://cs229.stanford.edu/[CS229: Machine Learning @ *Stanford*] +
http://cs224d.stanford.edu/[CS224d: Deep Learning for Natural Language Processing] +
http://cs231n.stanford.edu/[CS231n: Convolutional Neural Networks for Visual Recognition] +
https://learnml.today/[Object Detection with PyTorch] +
http://www.machinelearning.ru/wiki/index.php?title=%D0%9C%D0%B0%D1%88%D0%B8%D0%BD%D0%BD%D0%BE%D0%B5_%D0%BE%D0%B1%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D0%B5_%28%D0%BA%D1%83%D1%80%D1%81_%D0%BB%D0%B5%D0%BA%D1%86%D0%B8%D0%B9%2C_%D0%9A.%D0%92.%D0%92%D0%BE%D1%80%D0%BE%D0%BD%D1%86%D0%BE%D0%B2%29[Машинное обучение (курс лекций, К.В.Воронцов)] +
https://course.fast.ai/[Practical Deep Learning for Coders @ *fast.ai*] +
http://www0.cs.ucl.ac.uk/staff/d.silver/web/Teaching.html[UCL Course on Reinforcement Learning] +
https://selfdrivingcars.mit.edu/[MIT 6.S094: Deep Learning for Self-Driving Cars] +
https://www.youtube.com/playlist?list=PL-_cKNuVAYAVcBzEl66UZgCmqec_u7kcV[Вычисления на GPU. Основные подходы, архитектура, оптимизации @ *Лекториум*] +

== Books

https://mml-book.github.io/[Mathematics for Machine Learning] +
http://neuralnetworksanddeeplearning.com/[Neural Networks and Deep Learning] +
https://www.deeplearningbook.org/[Deep Learning] +

== Яндекс - КИТ

https://academy.yandex.ru/events/system_administration/kit_febr-2011/[Первый набор на Курсы информационных технологий @ *Яндекс*] +
https://academy.yandex.ru/events/system_administration/kit_oct-2011/[Второй набор на Курсы информационных технологий @ *Яндекс*] +
https://academy.yandex.ru/events/system_administration/kit_2012/[Третий набор на Курсы информационных технологий @ *Яндекс*] +
https://academy.yandex.ru/events/system_administration/kit_2013/[Четвертый набор на Курсы информационных технологий @ *Яндекс*] +
https://academy.yandex.ru/events/system_administration/kit_2014/[Пятый набор на Курсы информационных технологий @ *Яндекс*] +

== Яндекс - Школа анализа данных

https://yandexdataschool.ru/edu-process/courses/complexity[Сложность вычислений] +
https://yandexdataschool.ru/edu-process/courses/parallel[Параллельные и распределённые вычисления] +
https://yandexdataschool.ru/edu-process/courses/probability[Дискретный анализ и теория вероятностей] +
https://yandexdataschool.ru/edu-process/courses/algorithms[Алгоритмы и структуры данных] +
https://yandexdataschool.ru/edu-process/courses/machine-learning[Машинное обучение] +

== MIT OCW
https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-034-artificial-intelligence-fall-2010[Artificial Intelligence @ *MIT OCW*] +
https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-006-introduction-to-algorithms-fall-2011[Introduction to Algorithms @ *MIT OCW*] +
https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-046j-introduction-to-algorithms-sma-5503-fall-2005[Introduction to Algorithms @ *MIT OCW*] +
https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-042j-mathematics-for-computer-science-fall-2010[Mathematics for Computer Science @ *MIT OCW*] +
https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-851-advanced-data-structures-spring-2012[Advanced Data Structures @ *MIT OCW*] +

== Mathematics

=== YouTube Channels

https://www.youtube.com/channel/UCNLRwiQSPlAn_hiEM2yWIwg[Integrals ForYou @ *YouTube*] +
https://www.youtube.com/channel/UCtAIs1VCQrymlAnw3mGonhw[Flammable Maths @ *YouTube*] +
https://www.youtube.com/channel/UC5E5DQ5KaGeSHObCTsKM3lw[Cowan Academy @ *YouTube*] +
https://www.youtube.com/channel/UCoOjTxz-u5zU0W38zMkQIFw[Dr Peyam @ *YouTube*] +
https://www.youtube.com/user/MindYourDecisions[MindYourDecisions @ *YouTube*] +
https://www.youtube.com/user/blackpenredpen[blackpenredpen @ *YouTube*] +
https://www.youtube.com/user/LetssolveMP[LetsSolveMathProblems @ *YouTube*] +
