= Machine Learning

== Courses

https://deeplearning.mit.edu/[MIT Deep Learning and Artificial Intelligence Lectures] +
https://course.fast.ai/[Practical Deep Learning] +
https://dlcourse.ai/[Deep Learning на пальцах] +
https://huggingface.co/learn/audio-course/chapter0/introduction[Hugging Face Audio course] +
https://www.cloudskillsboost.google/journeys/118[Google | Introduction to Generative AI Learning Path] +
https://stanford-cs329s.github.io/[CS 329S: Machine Learning Systems Design] +
https://cs236g.stanford.edu/[CS236G: Generative Adversarial Networks (GANs)] +
https://fullstackdeeplearning.com/course/2022/[Full Stack Deep Learning - 2022 Course] +
https://developers.google.com/machine-learning[Google Machine Learning Education] +

== Books

https://mml-book.github.io/[Mathematics for Machine Learning] +
http://neuralnetworksanddeeplearning.com/[Neural Networks and Deep Learning] +
https://www.deeplearningbook.org/[Deep Learning] +
https://udlbook.github.io/udlbook/[Understanding Deep Learning] +

== Exploration

https://twimlai.com/[TWIML | The Voice of Machine Learning and Artificial Intelligence] +

== MLOps

https://mymlops.com/[Build your MLOps stack] +
https://ml-ops.org/[Machine Learning Operations] +
https://se-ml.github.io/[Software Engineering for Machine Learning] +
https://github.com/visenger/awesome-mlops[Awesome MLOps] +
https://developers.google.com/machine-learning/guides/rules-of-ml[Rules of Machine Learning: Best Practices for ML Engineering] +
https://www.gradio.app/[Gradio - Build & share delightful machine learning apps] +
https://streamlit.io/[Streamlit - A faster way to build and share data apps] +
https://greatexpectations.io/[Great Expectations - Have confidence in your data, no matter what] +
https://www.soda.io/[Soda - Test and deliver data that everyone can trust] +
https://cloud.google.com/architecture/mlops-continuous-delivery-and-automation-pipelines-in-machine-learning[MLOps: Continuous delivery and automation pipelines in machine learning] +
