= Software Engineering

== Learn

https://teachyourselfcs.com/[Teach Yourself Computer Science] +
https://www.interdb.jp/pg/[The Internals of PostgreSQL] +
https://use-the-index-luke.com/[SQL Indexing and Tuning e-Book] +
https://sre.google/books/[Google | SRE Books] +
https://abseil.io/resources/swe-book[Google | SWE Book] +
https://howhttps.works/[How HTTPS Works] +
https://interviewready.io/blog/white-papers-worth-reading-for-software-engineers[White Papers Worth Reading for Software Engineers] +
https://learn.microsoft.com/en-us/azure/architecture/patterns/[Microsoft | Cloud Design Patterns] +
https://h3h.github.io/leveling-matrix/[Software Engineer Leveling Matrix] +
https://github.com/bregman-arie/devops-exercises[Linux, Jenkins, AWS, SRE, Prometheus, Docker, Python, Ansible, Git, Kubernetes, Terraform, OpenStack, SQL, NoSQL, Azure, GCP, DNS, Elastic, Network, Virtualization. DevOps Interview Questions] +
https://malwareunicorn.org/#/workshops[Reverse Engineering Workshops] +
https://dancres.github.io/Pages/[A Distributed Systems Reading List ] +

https://css-tricks.com/[CSS-Tricks - Tips, Tricks, and Techniques on using Cascading Style Sheets.] +
https://www.fe.engineer/handbook/getting-started[Frontend Engineer Handbook] +

https://pwn.college/[pwn.college - core cybersecurity concepts in a hands-on fashion] +
https://web.stanford.edu/class/cs253/[Stanford - CS 253 Web Security] +

http://gaia.cs.umass.edu/kurose_ross/index.php[Computer Networking: A Top-Down Approach. 8th Edition] +
https://beej.us/guide/bgnet/[Beej's Guide to Network Programming. Using Internet Sockets] +

https://pages.cs.wisc.edu/~remzi/OSTEP/[Operating Systems: Three Easy Pieces] +
https://www.cs.cmu.edu/afs/cs/academic/class/15213-f16/www/index.html[CMU - Introduction to Computer Systems] +
http://csapp.cs.cmu.edu/3e/home.html[CMU - Book - Computer Systems: A Programmer's Perspective, 3/E (CS:APP3e)] +

https://interviewready.io/blog/white-papers-worth-reading-for-software-engineers[White papers that are worth your time] +
https://ui.dev/[JavaScript ecosystem courses] +

https://codedamn.com/[Change the world with codedamn] +

https://developers.google.com/tech-writing[Technical Writing Courses for Engineers] +
